### ISSUE TITLE
try Colorado data for error bar chart

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/chartjs-templates#3]
Please try this Colorado 2018 ACS 5-year data for the error bar chart

geo | median | median_moe | mean | mean_moe
-- | -- | -- | -- | --
Colorado | 68811 | 364 | 92520 | 416
Boulder County | 78642 | 1583 | 109466 | 2061
Boulder city | 66117 | 2590 | 102803 | 3614
Census tract 121.02 | 73396 | 10696 | 120588 | 19322

Please check my sources, and add links to the README?

2018 ACS 5-year median and mean household income for Colorado state, Boulder County, Boulder city
https://data.census.gov/cedsci/table?q=ACSDP1Y2018.DP03%20Colorado&t=Income%20and%20Poverty&g=0400000US08_0500000US08013_1600000US0807850&tid=ACSDP5Y2018.DP03&hidePreview=true

for census tract 121.02, located inside Boulder city
https://data.census.gov/cedsci/table?text=DP03&g=0500000US08013.140000&tid=ACSDP5Y2018.DP03&hidePreview=false

**Comment by ilyankou** [comment]
Done! I linked a smaller table with all four geographies in it (same values though): https://data.census.gov/cedsci/table?q=income&g=0400000US08_0500000US08013_1400000US08013012102_1600000US0807850&tid=ACSST5Y2018.S1901&hidePreview=true
