### ISSUE TITLE
How to get chart to load in Chrome locally?

### ISSUE THREAD

**Issue by windowshopr** [HandsOnDataViz/chartjs-templates#5]
This might be a really newb question, but I've copied the data.csv, index.html, and script.js to their own folder stored locally on my machine, but when I load index.html into chrome, no chart appears. All I see is the footer:

Source: CT Department of Education
Download data powering this visualization.

...with no chart above. How can I view the chart for testing locally?

**Comment by ilyankou** [comment]
Hi @windowshopr 

Not at all a newbie question! See README in this repo: https://github.com/HandsOnDataViz/chartjs-bar (*Why am I not seeing my chart when I open index.html in the browser?* section). There are a few suggested ways around it. Perhaps the easiest would be to follow the instructions from Alex Filatov's blog post: https://alfilatov.com/posts/run-chrome-without-cors/

Let me know if this helps!

P.S. We split this repo into individual repositories, such as `chartjs-bar` and `chartjs-line` etc, you can find links at the bottom of [this README](https://github.com/HandsOnDataViz/chartjs-bar).

**Comment by windowshopr** [comment]
Thanks for the reply. Unfortunately, the blog's solution didn't work for me. I created the shortcut with the arguments mentioned, then just drag and dropped the index.html onto that shortcut to open it up in that new browser instance, but the chart still didn't show up. I'll try the StackOverflow solution later and if that doesn't work, I'll try emulating a local web server. Kind of a headache, eh? lol thanks for the support! Will close issue for now.
